server:
  port: 10000

spring:
  application:
    name: studay-zero-gateway
  cloud:
    gateway:
      routes:
#        id唯一
        - id: studay-zero-user
#          uri  匹配后要访问的地址
          uri: http://127.0.0.1:7001
#          需要匹配的规则
          predicates:
            - Path=/user/**
#          https://blog.csdn.net/qq_61603262/article/details/127384412   翻译文
#          过滤器数组，在请求传递过程中，去除请求路径中的1级路径
          filters:
            - StripPrefix=1
        - id: studay-zero-system
          uri: http://127.0.0.1:7001
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: studay-zero-flink
            uri: http://127.0.0.1:7001
            predicates:
              - Path=/flink/**
            filters:
              - StripPrefix=1
        - id: studay-zero-pay
            uri: http://127.0.0.1:7001
            predicates:
              - Path=/pay/**
            filters:
              - StripPrefix=1