server:
  port: 10001

spring:
  application:
    name: study-zero-user
  datasource:
    url: jdbc:mysql://localhost:3306/zero?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 300
      jedis:
        pool:
          #连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          #连接池中的最大空闲连接
          max-idle: 500
          #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          #连接池中的最小空闲连接
          min-idle: 0
      lettuce:
        shutdown-timeout: 0


  # mybatis-plus相关配置
  mybatis-plus:
    global-config:
      db-config:
        logic-delete-field: deleFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    # mybatis-plus相关配置
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  logging:
    level:
      com.demo: debug