server:
  port: 7001
  servlet:
    context-path: /es


spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
      #修改配置文件 network.host: 127.0.0.1
      cluster-nodes: 127.0.0.1:9300
      #启动之后浏览器输入  http://localhost:9200/  查看名称
      cluster-name: elasticsearch

